CREATE TABLE admin_audit_logs (
    actor_id bigint,
    created_at timestamp(6) NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_id bigint,
    action varchar(255) NOT NULL,
    actor_name varchar(255),
    new_state varchar(255),
    old_state varchar(255),
    reason text,
    target_label varchar(255),
    target_type varchar(255)
);

CREATE TABLE analytics_events (
    created_at timestamp(6) NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kitchen_id bigint,
    user_id bigint,
    detail text,
    event_type varchar(255) NOT NULL,
    user_mobile varchar(255)
);

CREATE TABLE areas (
    active boolean NOT NULL,
    created_at timestamp(6),
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    updated_at timestamp(6),
    name varchar(160) NOT NULL UNIQUE
);

CREATE TABLE feature_flags (
    enabled boolean NOT NULL,
    limit_value integer,
    created_at timestamp(6),
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    updated_at timestamp(6),
    description text,
    display_name varchar(255) NOT NULL,
    feature_key varchar(255) NOT NULL UNIQUE,
    pricing_type varchar(255) NOT NULL CHECK (pricing_type IN ('FREE', 'PAID'))
);

CREATE TABLE users (
    blocked boolean NOT NULL,
    storefront_removed boolean NOT NULL,
    admin_area_id bigint,
    approved_at timestamp(6),
    approved_by_id bigint,
    area_id bigint,
    blocked_at timestamp(6),
    created_at timestamp(6),
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    society_id bigint,
    storefront_removed_at timestamp(6),
    updated_at timestamp(6),
    area varchar(255),
    blocked_reason text,
    building varchar(255),
    flat_house_number varchar(255),
    mobile_number varchar(255) UNIQUE,
    name varchar(255) NOT NULL,
    role varchar(255) NOT NULL CHECK (role IN ('BUYER', 'SELLER', 'ADMIN', 'SUPER_ADMIN')),
    seller_approval_status varchar(255) CHECK (seller_approval_status IN ('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_REQUESTED', 'SUSPENDED')),
    seller_status_reason text,
    society varchar(255),
    support_note text
);

CREATE TABLE societies (
    active boolean NOT NULL,
    area_id bigint NOT NULL,
    created_at timestamp(6),
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    updated_at timestamp(6),
    name varchar(160) NOT NULL,
    name_key varchar(160) NOT NULL,
    CONSTRAINT uq_societies_area_name_key UNIQUE (area_id, name_key)
);

CREATE TABLE kitchens (
    available_today boolean,
    rating double precision,
    storefront_paused boolean NOT NULL,
    created_at timestamp(6),
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id bigint NOT NULL,
    updated_at timestamp(6),
    seller_type varchar(30) NOT NULL CHECK (seller_type IN ('KITCHEN', 'HOMEMADE_PRODUCTS')),
    building varchar(255),
    description text,
    display_name varchar(255) NOT NULL,
    gallery_images text,
    image_url varchar(255),
    instagram_link varchar(255),
    name varchar(255) NOT NULL UNIQUE,
    order_deadline varchar(255),
    service_areas text,
    short_description varchar(255),
    society varchar(255),
    upi_id varchar(255),
    whatsapp_link varchar(255)
);

CREATE TABLE kitchen_served_societies (
    kitchen_id bigint NOT NULL,
    society_id bigint NOT NULL,
    PRIMARY KEY (kitchen_id, society_id)
);

CREATE TABLE products (
    available_date date,
    available_today boolean,
    available_until_date date,
    booked_quantity integer,
    is_preorder boolean,
    max_quantity integer,
    orders_paused boolean,
    price numeric(10,2) NOT NULL,
    rating double precision,
    remaining_quantity integer,
    created_at timestamp(6),
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kitchen_id bigint NOT NULL,
    updated_at timestamp(6),
    category varchar(255),
    cutoff_time varchar(255),
    description text,
    image_url varchar(255),
    name varchar(255) NOT NULL,
    order_window_end varchar(255),
    order_window_start varchar(255),
    preorder_type varchar(255) CHECK (preorder_type IN ('FIXED', 'FLEXIBLE')),
    price_unit varchar(255),
    ready_by_time varchar(255),
    time_slots varchar(255)
);

CREATE TABLE favourites (
    created_at timestamp(6),
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kitchen_id bigint,
    product_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT uq_favourites_user_kitchen UNIQUE (user_id, kitchen_id)
);

CREATE TABLE enquiries (
    acknowledged_at timestamp(6),
    acknowledged_by bigint,
    created_at timestamp(6),
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kitchen_id bigint NOT NULL,
    reminded_at timestamp(6),
    updated_at timestamp(6),
    user_id bigint NOT NULL,
    message text NOT NULL,
    preferred_date varchar(255),
    quantity varchar(255),
    reference_image_url varchar(255),
    status varchar(255) NOT NULL CHECK (status IN ('NEW', 'CONTACTED', 'CLOSED'))
);

CREATE TABLE ledger_events (
    amount numeric(10,2),
    buyer_id bigint,
    created_at timestamp(6),
    enquiry_id bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint,
    seller_id bigint,
    currency varchar(255),
    event_type varchar(255) NOT NULL,
    metadata text
);

CREATE TABLE notification_events (
    delivered boolean,
    created_at timestamp(6),
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    body text NOT NULL,
    title varchar(255) NOT NULL,
    user_mobile varchar(255)
);

CREATE TABLE orders (
    rating integer,
    total_amount numeric(10,2),
    acknowledged_at timestamp(6),
    acknowledged_by bigint,
    buyer_id bigint NOT NULL,
    created_at timestamp(6),
    delivered_at timestamp(6),
    delivery_updated_by bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kitchen_id bigint NOT NULL,
    order_time timestamp(6),
    reminded_at timestamp(6),
    updated_at timestamp(6),
    custom_instructions text,
    delivery_status varchar(255) CHECK (delivery_status IN ('NOT_DELIVERED', 'DELIVERED')),
    order_number varchar(255) NOT NULL UNIQUE,
    order_status varchar(255) NOT NULL CHECK (order_status IN ('DRAFT', 'ORDERED', 'CONFIRMED', 'READY', 'DELIVERED', 'COMPLETED', 'CANCELLED')),
    payment_status varchar(255) NOT NULL CHECK (payment_status IN ('PENDING', 'PAID', 'WILL_PAY_LATER'))
);

CREATE TABLE order_items (
    price numeric(10,2) NOT NULL,
    quantity integer NOT NULL,
    scheduled_date date,
    created_at timestamp(6),
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id bigint,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    updated_at timestamp(6),
    scheduled_slot varchar(255)
);

CREATE TABLE order_daily_aggregates (
    agg_day date NOT NULL,
    order_count integer NOT NULL,
    recorded_order_value numeric(14,2) NOT NULL,
    area_id bigint,
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id bigint,
    society_id bigint,
    updated_at timestamp(6),
    area_name varchar(255),
    category varchar(255),
    seller_name varchar(255),
    society_name varchar(255)
);

CREATE TABLE platform_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    updated_at timestamp(6),
    setting_key varchar(255) NOT NULL UNIQUE,
    setting_value text
);

CREATE TABLE quick_posts (
    posted_date date NOT NULL,
    created_at timestamp(6) NOT NULL,
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kitchen_id bigint NOT NULL,
    request_id varchar(80) NOT NULL UNIQUE,
    image_data text,
    message text NOT NULL
);

CREATE TABLE recurring_schedules (
    default_quantity integer,
    end_date date NOT NULL,
    ongoing boolean NOT NULL,
    start_date date NOT NULL,
    created_at timestamp(6),
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id bigint NOT NULL UNIQUE,
    updated_at timestamp(6),
    default_order_close_time varchar(255),
    default_ready_by_time varchar(255),
    recurrence_days varchar(255) NOT NULL,
    status varchar(255) NOT NULL CHECK (status IN ('ACTIVE', 'ENDED'))
);

CREATE TABLE occurrences (
    occurrence_date date NOT NULL,
    orders_paused boolean NOT NULL,
    quantity integer,
    sold_out boolean NOT NULL,
    created_at timestamp(6),
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    schedule_id bigint NOT NULL,
    updated_at timestamp(6),
    order_close_time varchar(255),
    ready_by_time varchar(255),
    status varchar(255) NOT NULL CHECK (status IN ('SCHEDULED', 'LIVE', 'ORDERS_CLOSED', 'SOLD_OUT', 'ENDED')),
    CONSTRAINT uq_occurrence_schedule_date UNIQUE (schedule_id, occurrence_date)
);

CREATE TABLE occurrence_overrides (
    orders_paused boolean,
    quantity integer,
    quantity_overridden boolean NOT NULL,
    sold_out boolean,
    created_at timestamp(6),
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurrence_id bigint NOT NULL,
    updated_at timestamp(6),
    order_close_time varchar(255),
    ready_by_time varchar(255),
    CONSTRAINT uq_override_occurrence UNIQUE (occurrence_id)
);

CREATE TABLE seller_feature_grants (
    granted boolean NOT NULL,
    limit_override integer,
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id bigint NOT NULL,
    updated_at timestamp(6),
    feature_key varchar(255) NOT NULL,
    CONSTRAINT uq_seller_feature_grants_seller_feature UNIQUE (seller_id, feature_key)
);

CREATE TABLE seller_templates (
    max_quantity integer,
    price numeric(10,2) NOT NULL,
    created_at timestamp(6),
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seller_id bigint NOT NULL,
    updated_at timestamp(6),
    category varchar(255) CHECK (category IN ('BREAKFAST', 'LUNCH', 'DINNER', 'SNACKS', 'SPECIAL')),
    cutoff_time varchar(255),
    description text,
    image_url varchar(255),
    name varchar(255) NOT NULL,
    order_window_end varchar(255),
    order_window_start varchar(255),
    price_unit varchar(255),
    ready_by_time varchar(255)
);

CREATE INDEX idx_audit_action ON admin_audit_logs (action);
CREATE INDEX idx_audit_target ON admin_audit_logs (target_type, target_id);
CREATE INDEX idx_audit_created ON admin_audit_logs (created_at);
CREATE INDEX idx_analytics_type ON analytics_events (event_type);
CREATE INDEX idx_analytics_created ON analytics_events (created_at);
CREATE INDEX idx_agg_day ON order_daily_aggregates (agg_day);
CREATE INDEX idx_agg_seller ON order_daily_aggregates (seller_id);
CREATE INDEX idx_occurrence_schedule ON occurrences (schedule_id);
CREATE INDEX idx_occurrence_date ON occurrences (occurrence_date);
CREATE INDEX idx_override_occurrence ON occurrence_overrides (occurrence_id);

ALTER TABLE users ADD CONSTRAINT fk_users_society FOREIGN KEY (society_id) REFERENCES societies (id);
ALTER TABLE users ADD CONSTRAINT fk_users_area FOREIGN KEY (area_id) REFERENCES areas (id);
ALTER TABLE users ADD CONSTRAINT fk_users_approved_by FOREIGN KEY (approved_by_id) REFERENCES users (id);
ALTER TABLE societies ADD CONSTRAINT fk_societies_area FOREIGN KEY (area_id) REFERENCES areas (id);
ALTER TABLE kitchens ADD CONSTRAINT fk_kitchens_seller FOREIGN KEY (seller_id) REFERENCES users (id);
ALTER TABLE kitchen_served_societies ADD CONSTRAINT fk_kitchen_societies_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens (id);
ALTER TABLE kitchen_served_societies ADD CONSTRAINT fk_kitchen_societies_society FOREIGN KEY (society_id) REFERENCES societies (id);
ALTER TABLE products ADD CONSTRAINT fk_products_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens (id);
ALTER TABLE favourites ADD CONSTRAINT fk_favourites_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE favourites ADD CONSTRAINT fk_favourites_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens (id);
ALTER TABLE favourites ADD CONSTRAINT fk_favourites_product FOREIGN KEY (product_id) REFERENCES products (id);
ALTER TABLE enquiries ADD CONSTRAINT fk_enquiries_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE enquiries ADD CONSTRAINT fk_enquiries_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens (id);
ALTER TABLE enquiries ADD CONSTRAINT fk_enquiries_acknowledged_by FOREIGN KEY (acknowledged_by) REFERENCES users (id);
ALTER TABLE orders ADD CONSTRAINT fk_orders_buyer FOREIGN KEY (buyer_id) REFERENCES users (id);
ALTER TABLE orders ADD CONSTRAINT fk_orders_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens (id);
ALTER TABLE orders ADD CONSTRAINT fk_orders_delivery_updated_by FOREIGN KEY (delivery_updated_by) REFERENCES users (id);
ALTER TABLE orders ADD CONSTRAINT fk_orders_acknowledged_by FOREIGN KEY (acknowledged_by) REFERENCES users (id);
ALTER TABLE order_items ADD CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id);
ALTER TABLE order_items ADD CONSTRAINT fk_order_items_product FOREIGN KEY (product_id) REFERENCES products (id);
ALTER TABLE order_items ADD CONSTRAINT fk_order_items_occurrence FOREIGN KEY (occurrence_id) REFERENCES occurrences (id);
ALTER TABLE recurring_schedules ADD CONSTRAINT fk_recurring_schedules_product FOREIGN KEY (product_id) REFERENCES products (id);
ALTER TABLE occurrences ADD CONSTRAINT fk_occurrences_schedule FOREIGN KEY (schedule_id) REFERENCES recurring_schedules (id);
ALTER TABLE occurrence_overrides ADD CONSTRAINT fk_occurrence_overrides_occurrence FOREIGN KEY (occurrence_id) REFERENCES occurrences (id);
ALTER TABLE quick_posts ADD CONSTRAINT fk_quick_posts_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens (id);
ALTER TABLE seller_templates ADD CONSTRAINT fk_seller_templates_seller FOREIGN KEY (seller_id) REFERENCES users (id);
