# Application Name
spring.application.name=my-first-spring-api

# Server Port
server.port=8080

# Configure logging levels
logging.level.com.example.my_first_spring_api=DEBUG

# Active Profile
spring.profiles.active=dev