-- SocioMart Schema SQL
-- Note: Tables are auto-created by JPA/Hibernate (ddl-auto=update).
-- This script is intentionally left minimal for reference only.
-- Use data.sql for demo data seeding.

-- The following tables are created automatically by JPA:
-- - users (id, name, mobile_number, flat_house_number, society, building, role, seller_approval_status, approved_at, created_at, updated_at)
-- - kitchen (id, slug, name, short_description, description, society, building, whatsapp_link, instagram_link, upi_id, available_today, order_deadline, rating, seller_id, created_at, updated_at)
-- - product (id, name, description, price, price_unit, image_url, available_today, max_quantity, remaining_quantity, rating, is_preorder, kitchen_id, created_at, updated_at)
-- - orders (id, buyer_id, kitchen_id, order_status, payment_status, total_amount, created_at, updated_at)
-- - order_item (id, order_id, product_id, quantity, price, product_name)
-- - platform_setting (id, setting_key, setting_value)
-- - feature_flag (id, feature_key, enabled, mode, default_limit)
-- - seller_feature_grant (id, seller_id, feature_key, enabled, custom_limit)
-- - otp_verification (id, mobile_number, otp_code, expires_at, verified, created_at)
-- - analytics_event (id, event_type, user_id, metadata, created_at)
