package com.example.my_first_spring_api.dto;
import com.example.my_first_spring_api.model.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
public class SellerOrderSummaryRowDto {
 private Long id; private String orderNumber; private BigDecimal totalAmount; private PaymentStatus paymentStatus; private OrderStatus orderStatus; private LocalDateTime createdAt,orderTime,updatedAt; private OrderDto.KitchenSummary kitchen; private List<OrderItemDto> items; private BuyerSummary buyer; private String customInstructions; private LocalDateTime acknowledgedAt; private Long acknowledgedBySellerId;
 public static class BuyerSummary { private String name,flatHouseNumber,society,building; public String getName(){return name;} public void setName(String v){name=v;} public String getFlatHouseNumber(){return flatHouseNumber;} public void setFlatHouseNumber(String v){flatHouseNumber=v;} public String getSociety(){return society;} public void setSociety(String v){society=v;} public String getBuilding(){return building;} public void setBuilding(String v){building=v;} }
 public Long getId(){return id;} public void setId(Long v){id=v;} public String getOrderNumber(){return orderNumber;} public void setOrderNumber(String v){orderNumber=v;} public BigDecimal getTotalAmount(){return totalAmount;} public void setTotalAmount(BigDecimal v){totalAmount=v;} public PaymentStatus getPaymentStatus(){return paymentStatus;} public void setPaymentStatus(PaymentStatus v){paymentStatus=v;} public OrderStatus getOrderStatus(){return orderStatus;} public void setOrderStatus(OrderStatus v){orderStatus=v;} public LocalDateTime getCreatedAt(){return createdAt;} public void setCreatedAt(LocalDateTime v){createdAt=v;} public LocalDateTime getOrderTime(){return orderTime;} public void setOrderTime(LocalDateTime v){orderTime=v;} public LocalDateTime getUpdatedAt(){return updatedAt;} public void setUpdatedAt(LocalDateTime v){updatedAt=v;} public OrderDto.KitchenSummary getKitchen(){return kitchen;} public void setKitchen(OrderDto.KitchenSummary v){kitchen=v;} public List<OrderItemDto> getItems(){return items;} public void setItems(List<OrderItemDto> v){items=v;} public BuyerSummary getBuyer(){return buyer;} public void setBuyer(BuyerSummary v){buyer=v;} public String getCustomInstructions(){return customInstructions;} public void setCustomInstructions(String v){customInstructions=v;} public LocalDateTime getAcknowledgedAt(){return acknowledgedAt;} public void setAcknowledgedAt(LocalDateTime v){acknowledgedAt=v;} public Long getAcknowledgedBySellerId(){return acknowledgedBySellerId;} public void setAcknowledgedBySellerId(Long v){acknowledgedBySellerId=v;}
}